import { ArrowLeft } from "lucide-react";
import { Link } from "react-router-dom";
import { useLanguage } from "@/contexts/LanguageContext";
import SEOHead from "@/components/SEOHead";

const PrivacyPolicy = () => {
  const { t } = useLanguage();

  return (
    <div className="min-h-screen luxury-bg text-white">
      <SEOHead
        title="Privacy Policy — M-Monogram"
        description="How M-Monogram collects, stores and uses the personal data you submit through the site."
        path="/privacy-policy"
      />
      {/* Back Button - positioned below logo */}
      <div className="absolute left-4 sm:left-6 md:left-12 z-20" style={{ top: `calc(env(safe-area-inset-top, 0px) + 6rem)` }}>
        <Link
          to="/"
          className="flex items-center gap-2 text-white/70 hover:text-white transition-all duration-300 font-body text-xs sm:text-sm uppercase tracking-widest cursor-pointer touch-target border border-white/20 hover:border-white/40 px-4 py-2.5 sm:px-5 sm:py-3 bg-premium-black/50 backdrop-blur-md rounded-none"
        >
          <ArrowLeft className="w-4 h-4" />
          {t("nav.home")}
        </Link>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-6 pb-12 pt-64">
        <h1 className="font-display text-3xl md:text-4xl tracking-wide mb-2">
          Privacy Policy
        </h1>
        <p className="text-white/40 font-body text-sm mb-12">
          Last updated: March 26, 2023
        </p>

        <div className="prose prose-invert prose-sm max-w-none font-body space-y-8">
          <p className="text-white/70 leading-relaxed">
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          <p className="text-white/70 leading-relaxed">
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
          </p>

          <section>
            <h2 className="font-display text-xl tracking-wide text-white mb-4">Interpretation and Definitions</h2>
            
            <h3 className="font-display text-lg text-white/90 mb-3">Interpretation</h3>
            <p className="text-white/70 leading-relaxed">
              The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>

            <h3 className="font-display text-lg text-white/90 mt-6 mb-3">Definitions</h3>
            <p className="text-white/70 mb-4">For the purposes of this Privacy Policy:</p>
            <ul className="space-y-3 text-white/70">
              <li><strong className="text-white">Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong className="text-white">Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to MetaGarage. For the purpose of the GDPR, the Company is the Data Controller.</li>
              <li><strong className="text-white">Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
              <li><strong className="text-white">Country</strong> refers to: United Arab Emirates</li>
              <li><strong className="text-white">Data Controller</strong>, for the purposes of the GDPR (General Data Protection Regulation), refers to the Company as the legal person which alone or jointly with others determines the purposes and means of the processing of Personal Data.</li>
              <li><strong className="text-white">Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
              <li><strong className="text-white">Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong className="text-white">Service</strong> refers to the Website.</li>
              <li><strong className="text-white">Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
              <li><strong className="text-white">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
              <li><strong className="text-white">Website</strong> refers to MetaGarage, accessible from https://metagarage.ae</li>
              <li><strong className="text-white">You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-xl tracking-wide text-white mb-4">Collecting and Using Your Personal Data</h2>
            
            <h3 className="font-display text-lg text-white/90 mb-3">Types of Data Collected</h3>
            
            <h4 className="font-display text-base text-white/80 mb-2">Personal Data</h4>
            <p className="text-white/70 leading-relaxed mb-4">
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
            </p>
            <ul className="list-disc list-inside space-y-1 text-white/70 mb-6">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Address, State, Province, ZIP/Postal code, City</li>
              <li>Usage Data</li>
            </ul>

            <h4 className="font-display text-base text-white/80 mb-2">Usage Data</h4>
            <p className="text-white/70 leading-relaxed">
              Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl tracking-wide text-white mb-4">Tracking Technologies and Cookies</h2>
            <p className="text-white/70 leading-relaxed mb-4">
              We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
            </p>
            <ul className="space-y-3 text-white/70">
              <li><strong className="text-white">Necessary / Essential Cookies:</strong> These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features.</li>
              <li><strong className="text-white">Functionality Cookies:</strong> These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference.</li>
              <li><strong className="text-white">Tracking and Performance Cookies:</strong> These Cookies are used to track information about traffic to the Website and how users use the Website.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-xl tracking-wide text-white mb-4">Use of Your Personal Data</h2>
            <p className="text-white/70 mb-4">The Company may use Personal Data for the following purposes:</p>
            <ul className="space-y-2 text-white/70">
              <li>• To provide and maintain our Service, including to monitor the usage of our Service.</li>
              <li>• To manage Your Account: to manage Your registration as a user of the Service.</li>
              <li>• For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</li>
              <li>• To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
              <li>• To provide You with news, special offers and general information about other goods, services and events.</li>
              <li>• To manage Your requests: To attend and manage Your requests to Us.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-xl tracking-wide text-white mb-4">Retention of Your Personal Data</h2>
            <p className="text-white/70 leading-relaxed">
              The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl tracking-wide text-white mb-4">Transfer of Your Personal Data</h2>
            <p className="text-white/70 leading-relaxed">
              Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl tracking-wide text-white mb-4">Security of Your Personal Data</h2>
            <p className="text-white/70 leading-relaxed">
              The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl tracking-wide text-white mb-4">GDPR Privacy</h2>
            <h3 className="font-display text-lg text-white/90 mb-3">Your Rights under the GDPR</h3>
            <p className="text-white/70 mb-4">You have the right under this Privacy Policy, and by law if You are within the EU, to:</p>
            <ul className="space-y-2 text-white/70">
              <li>• Request access to Your Personal Data.</li>
              <li>• Request correction of the Personal Data that We hold about You.</li>
              <li>• Object to processing of Your Personal Data.</li>
              <li>• Request erasure of Your Personal Data.</li>
              <li>• Request the transfer of Your Personal Data.</li>
              <li>• Withdraw Your consent.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-xl tracking-wide text-white mb-4">Children's Privacy</h2>
            <p className="text-white/70 leading-relaxed">
              Our Service does not address anyone under the age of 18. We do not knowingly collect personally identifiable information from anyone under the age of 18. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl tracking-wide text-white mb-4">Links to Other Websites</h2>
            <p className="text-white/70 leading-relaxed">
              Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl tracking-wide text-white mb-4">Changes to this Privacy Policy</h2>
            <p className="text-white/70 leading-relaxed">
              We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl tracking-wide text-white mb-4">Contact Us</h2>
            <p className="text-white/70 leading-relaxed">
              If you have any questions about this Privacy Policy, You can contact us:
            </p>
            <p className="text-white/70 mt-2">
              By email: <a href="mailto:m_monogram@mail.ru" className="text-white hover:underline">m_monogram@mail.ru</a>
            </p>
          </section>
        </div>
      </div>

      {/* Footer */}
      <div className="border-t border-white/10">
        <div className="max-w-4xl mx-auto px-6 py-6 text-center">
          <p className="text-white/30 font-body text-xs">
            © 2025 M-Monogram. All rights reserved.
          </p>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
